### ISSUE TITLE
Testing script

### ISSUE THREAD

**Issue by mikkoyli** [ouspg/cloudfuzzer#10]
Good image is needed that founds more samples when fuzzing.

Results autosync with cronjob

**Comment by attekett** [comment]
We don't actually need fuzzing for this. We should just make a Dockerfile with a simple script that creates "new samples" periodically.

In simplest it could just a while loop that does "sleep 1; let count++; echo $count > /samples/$count; echo $count >> /samples/file-list". Maybe add a variable which adds some prefix for the file names, if multiple containers are executed in the test.

Then modify the gce-test so that we could specify the test folder to be uploaded and executed in GCE.

Create tests folder, add folder for the Dockerfile and configuration and create a script that build docker image, runs gce-test and verifies that all samples are synced periodically and with manual sync.

When finalizing the periodical sync, we have to add a variable for sync interval control, so that we don't have to wait for N minutes before we can verify that the results.
